### PR TITLE
nvm: do not depend on `master`

### PR DESCRIPTION
**Pull request by ljharb**
I'm the maintainer of `nvm`. The master branch is unstable, and I break it all the time, intentionally. Please do not depend on it; only depend on tagged releases.

Will fix https://github.com/creationix/nvm/pull/1381#issuecomment-272535291 / https://github.com/creationix/nvm/issues/1384

### CODE REVIEW

**Comment by ljharb** [comment]
@atomsfat any chance of getting this merged?

**Comment by ZeeCoder** [comment]
Yeah finding this I wouldn't even consider using the plugin. 🤔

**Comment by atomsfat** [comment]
Sorry guys I had been solved here:

https://github.com/jenkinsci/nvm-wrapper-plugin/pull/4/commits/bb70f9c89db02ace8a9e1d419a23db589007d4ea#diff-d47fc45202e15f5436a9a14549660831R24

**Comment by ljharb** [comment]
Thanks!

**Pull request closed without merging**
