### PR TITLE
Added Jenkins workflow / pipeline step.

### PR DESCRIPTION
**Pull request by jSherz**
Usage is:

```
nvm(version: 'v6.1.2') {
  sh 'env'
}
```

### CODE REVIEW

**Comment by ejohansson** [comment]
any updates on this pull request?

**Comment by jSherz** [comment]
Closing this PR as it includes updates to the README that are specific to my fork.

@ejohansson This has been open for a while and so I resorted to building & installing manually I'm afraid.

**Comment by atomsfat** [comment]
awesome I would integrate this. 

- 

 🍻

**Comment by atomsfat** [comment]
Hi, everyone the merge is on this branch https://github.com/jenkinsci/nvm-wrapper-plugin/pull/5

**Pull request closed without merging**
